name: Linux build

on:
  workflow_dispatch:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --shamefully-hoist --no-frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Package
        run: pnpm run pack:linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to release
        run: |
          gh release upload "${{ github.event.release.tag_name }}" \
            dist/*.zip \
            dist/*.deb \
            dist/*.AppImage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
